version: "3"

services:
  ansible-controller:
    build:
      context: ./ansible
      dockerfile: Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./ansible:/ansible
    networks:
      - app_network

  app:
    build:
      context: ./src
      dockerfile: Dockerfile
    networks:
      - app_network
    volumes:
      - ./src:/app
    entrypoint: ["/app/laba1.sh", "START"]

networks:
  app_network:
    driver: bridge
